{{- $config := .Values.seafile.configs.seafileDataVolume -}}
{{- if and (include "seafile.seafileDataVolume.enabled" . | eq "true") (not ($config).existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-data
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ include "seafile.seafileDataVolume.storage" . }}
  {{- if ($config).storageClassName }}
  storageClassName: {{ $config.storageClassName }}
  {{- end }}
{{- end }}
