{{- if .Values.seafile.secretsMap }}
apiVersion: v1
kind: Secret
metadata:
  name: seafile-secret
  labels: {{ include "seafile.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.seafile.secretsMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
