apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seafile.fullname" . }}
  labels: {{ include "seafile.labels" . | nindent 4 }}
spec:
  replicas: {{ if .Values.seafile.pause }} 0 {{ else }} 1 {{ end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "seafile.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "seafile.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      enableServiceLinks: false
      {{- with .Values.seafile.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if include "seafile.seafileDataVolume.enabled" . | eq "true" }}
      initContainers:
        - name: set-ownership
          image: busybox
          command: ['sh', '-c', 'chown -R root:root /shared']
          volumeMounts:
          - name: seafile-data
            mountPath: /shared
      {{- end }}
      containers:
      - name: seafile
        {{- with .Values.seafile.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: {{ include "seafile.image" . }}
        imagePullPolicy: Always
        env:
          - name: SEAFILE_AI_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: seafile-secret
                key: JWT_PRIVATE_KEY
          {{- if .Values.moco.clusterName }}
          - name: SEAFILE_MYSQL_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: moco-{{ .Values.moco.clusterName }}
                key: WRITABLE_PASSWORD
          {{- end }}
        envFrom:
          - configMapRef:
              name: seafile-env
          - secretRef:
              name: seafile-secret
          {{- if .Values.seafile.extraEnv }}
            {{- toYaml .Values.seafile.extraEnv | nindent 10 }}
          {{- end }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: webdav
          containerPort: 8080
          protocol: TCP
        {{- if include "seafile.seafileDataVolume.enabled" . | eq "true" }}
        volumeMounts:
          - name: seafile-data
            mountPath: /shared
          {{- range .Values.seafile.extraVolumes }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
            {{- if .readOnly }}
            readOnly: {{ .readOnly }}
            {{- end }}
          {{- end }}
        {{- end }}
        resources: {{- toYaml .Values.seafile.extraResources | nindent 10 }}
      {{- if include "seafile.seafileDataVolume.enabled" . | eq "true" }}
      volumes:
        - name: seafile-data
          persistentVolumeClaim:
            claimName: {{ include "seafile.seafileDataVolume.claimName" . }}
        {{- range .Values.seafile.extraVolumes }}
        - name: {{ .name }}
          {{- toYaml .volumeInfo | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- with .Values.seafile.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
