apiVersion: v2
name: seafile
type: application
version: 13.0.2
appVersion: "13.0"
icon: https://www.seafile.com/media/img/seafile-logo.png
home: https://github.com/schmitzis/helm-charts
description: Seafile Server, Reliable and Performant File Sync and Share Solution on Kubernetes
keywords:
  - cloud
  - file
  - share
  - sync
sources:
  - https://github.com/schmitzis/helm-charts
  - https://github.com/haiwen/seafile
